#!/bin/sh
# Like mv $1 $2, but if the files are the same, just delete $1.
# Status is 0 if $2 is changed, 1 otherwise.
quiet=
if test $1 = "-q"; then
  quiet=1
  shift
fi
if test -r $2; then
  if cmp -s $1 $2; then
    test $quiet || echo $2 is unchanged
    rm -f $1
    exit 1
  else
    mv -f $1 $2
  fi
else
  mv -f $1 $2
fi
